name: wuwa
channels:
  - defaults
dependencies:
  - ca-certificates=2025.11.4=haa95532_0
  - libffi=3.4.4=hd77b12b_1
  - openssl=3.0.18=h543e019_0
  - pip=24.2=py38haa95532_0
  - python=3.8.20=h8205438_0
  - setuptools=75.1.0=py38haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.44.0=py38haa95532_0
  - pip:
    - blinker==1.8.2
    - click==8.1.8
    - colorama==0.4.6
    - easyocr==1.7.2
    - exceptiongroup==1.3.1
    - filelock==3.16.1
    - flask==3.0.3
    - flask-cors==5.0.0
    - fsspec==2025.3.0
    - imageio==2.35.1
    - importlib-metadata==8.5.0
    - iniconfig==2.1.0
    - itsdangerous==2.2.0
    - jinja2==3.1.6
    - lazy-loader==0.4
    - markupsafe==2.1.5
    - mpmath==1.3.0
    - networkx==3.1
    - ninja==1.13.0
    - numpy==1.24.4
    - opencv-python-headless==4.12.0.88
    - packaging==25.0
    - pillow==10.4.0
    - pluggy==1.5.0
    - pyclipper==1.3.0.post6
    - pytest==8.3.5
    - python-bidi==0.6.7
    - pywavelets==1.4.1
    - pyyaml==6.0.3
    - scikit-image==0.21.0
    - scipy==1.10.1
    - shapely==2.0.7
    - sympy==1.13.3
    - tifffile==2023.7.10
    - tomli==2.3.0
    - torch==2.4.1
    - torchvision==0.19.1
    - typing-extensions==4.13.2
    - werkzeug==3.0.6
    - zipp==3.20.2
prefix: C:\Users\a123t\anaconda3\envs\wuwa
